### ISSUE TITLE
gitlab3.exceptions.MissingRequiredAttribute

### ISSUE THREAD

**Issue by icyleaf** [doctormo/python-gitlab3#21]
i using gitlab-mirrors to mirror github repo, it always throw exception during mirror `https://github.com/AFNetworking/AFNetworking.git`, other repo is ok

``` bash
Traceback (most recent call last):
  File "lib/manage_gitlab_project.py", line 109, in <module>
    found_project=createproject(project_name)
  File "lib/manage_gitlab_project.py", line 95, in createproject
    new_project=git.add_project(pname,description=description,**project_options)
  File "build/bdist.linux-x86_64/egg/gitlab3/__init__.py", line 184, in fn
  File "build/bdist.linux-x86_64/egg/gitlab3/__init__.py", line 418, in _post
  File "build/bdist.linux-x86_64/egg/gitlab3/__init__.py", line 435, in _request
  File "build/bdist.linux-x86_64/egg/gitlab3/__init__.py", line 411, in _check_status_code
gitlab3.exceptions.MissingRequiredAttribute: URL: http://gitlab.dev/api/v3/projects, Data: {'wall_enabled': 'false', 'snippets_enabled': 'false', 'merge_requests_enabled': 'false', 'name': 'AFNetworking-AFNetworking', 'issues_enabled': 'false', 'wiki_enabled': 'false', 'public': 'true', 'description': 'Mirror of https://github.com/AFNetworking/AFNetworking.git'}
```

Gitlab: 7.8.1
Gitlab3: 0.5.4

**Comment by samrocketman** [comment]
Perhaps take a look how my project is using python-gitlab3.

https://github.com/samrocketman/gitlab-mirrors/blob/master/lib/manage_gitlab_project.py

I haven't read too much into your issue so I'm not entirely sure where your error lies.

**Comment by icyleaf** [comment]
mirror `github/mruby-ios` using gitmirror is ok

``` bash
Resolving gitlab remote.
Creating mirror from https://github.com/jzzocc/mruby-iOS.git
remote: Counting objects: 588, done.
remote: Total 588 (delta 0), reused 0 (delta 0), pack-reused 588
接收对象中: 100% (588/588), 20.69 MiB | 353 KiB/s, done.
处理 delta 中: 100% (268/268), done.
Adding gitlab remote to project.
Checking the mirror into gitlab.
Counting objects: 588, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (303/303), done.
Writing objects: 100% (588/588), 20.69 MiB | 19.32 MiB/s, done.
Total 588 (delta 268), reused 588 (delta 268)
To git@gitlab.dev:mirrors/jzzocc-mruby-ios.git
 * [new branch]      master -> master
 * [new tag]         0.0.1 -> 0.0.1
 * [new tag]         0.0.2 -> 0.0.2
 * [new tag]         0.1 -> 0.1
 * [new tag]         1.0.0 -> 1.0.0
 * [new tag]         1.1.0 -> 1.1.0
```

**Comment by icyleaf** [comment]
sorry, wrong place :(
