### ISSUE TITLE
Error when adding ssh key to user

### ISSUE THREAD

**Issue by dpasqualin** [doctormo/python-gitlab3#9]
I'm logged in as admin and I'm trying to add a ssh key to a user using the command gl_user.add_ssh_key(title, ssh_key). I get the following exception

```
Traceback (most recent call last):
  File "./link_users_to_projects.py", line 136, in <module>
    gl_user.add_ssh_key(title, ssh_key)
  File "/usr/local/lib/python2.7/dist-packages/gitlab3-0.5.2-py2.7.egg/gitlab3/__init__.py", line 184, in fn
    data = parent._post(api._uq_url, data=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gitlab3-0.5.2-py2.7.egg/gitlab3/__init__.py", line 416, in _post
    return self._request(requests.post, api_url, addl_keys, data)
  File "/usr/local/lib/python2.7/dist-packages/gitlab3-0.5.2-py2.7.egg/gitlab3/__init__.py", line 433, in _request
    self._check_status_code(r.status_code, url, data)
  File "/usr/local/lib/python2.7/dist-packages/gitlab3-0.5.2-py2.7.egg/gitlab3/__init__.py", line 409, in _check_status_code
    raise self._code_to_exc[status_code](msg)
gitlab3.exceptions.ResourceNotFound: URL: https://gitlab.c3sl.ufpr.br/api/v3/users/114/keys, Data: {'key': 'ssh-dss AAAAB3NzaC1kc3MAAACBAOo/7hdfdVrw/nviuqk8RyJr1U1zkgwrrvio+qqtVBSLyW97xQreSwuWeGpPWYB8b2yMMW8wz34EUfPHtiiKU02ZkxOEmaaza+KojizhoPNkM+l6pUwmz/2rSi176VLmOXSdRFb3Ng58iDvFCyjwFK8NqVHELXjjYdOQJzxW2WLtAAAAFQC3nj4MtGVrIvivSi63okCUi4TglQAAAIEA0vk5nhFca6K7XW8aJD6RxQpBNaad06l0u8FJU6CxmNNEDW2K07n91NoFh946pn4pV5YnuYOCt5nedPmggGebQ7kRfWCZcdgviAqlYyuV+1r8VPlLgOg+R+eV6XTNWOSgd1aXckXI5TSWbH7kV4dDUr6xV8jtt6sefRf1A+f7q4AAAACBALXQRBTWkHwxquPZi2ui4yRTubNdtatgEjSFmoC1V+wrA9Z5xl3ViQl2eOKlQCQDfHaJFzC/UvBkilggUZfL4NyuSWueL5XR02iA6BjJEGHHSORsSG0NrgIIupwd5VSB+4oSWOagAjhm5laZYCWFnuqS7J9l2h3x21xt3W0UC6Ib eap08@mumm', 'title': 'eap08@mumm'}

```

**Comment by dpasqualin** [comment]
I was looking into Gitlab log files and I got the following after running the comand mentioned above:

```
  Key Exists (0.3ms)  SELECT 1 AS one FROM `keys` WHERE `keys`.`key` = BINARY 'ssh-dss AAAAB3NzaC1kc3MAAACBAOo/7hdfdVrw/nviuqk8RyJr1U1zkgwrrvio+qqtVBSLyW97xQreSwuWeGpPWYB8b2yMMW8wz34EUfPHtiiKU02ZkxOEmaaza+KojizhoPNkM+l6pUwmz/2rSi176VLmOXSdRFb3Ng58iDvFCyjwFK8NqVHELXjjYdOQJzxW2WLtAAAAFQC3nj4MtGVrIvivSi63okCUi4TglQAAAIEA0vk5nhFca6K7XW8aJD6RxQpBNaad06l0u8FJU6CxmNNEDW2K07n91NoFh946pn4pV5YnuYOCt5nedPmggGebQ7kRfWCZcdgviAqlYyuV+1r8VPlLgOg+R+eV6XTNWOSgd1aXckXI5TSWbH7kV4dDUr6xV8jtt6sefRf1A+f7q4AAAACBALXQRBTWkHwxquPZi2ui4yRTubNdtatgEjSFmoC1V+wrA9Z5xl3ViQl2eOKlQCQDfHaJFzC/UvBkilggUZfL4NyuSWueL5XR02iA6BjJEGHHSORsSG0NrgIIupwd5VSB+4oSWOagAjhm5laZYCWFnuqS7J9l2h3x21xt3W0UC6Ib eap08@mumm' LIMIT 1
  Key Exists (0.3ms)  SELECT 1 AS one FROM `keys` WHERE `keys`.`fingerprint` = BINARY 'd4:d3:6a:25:c5:3a:1c:a5:8e:8b:4d:b2:5a:ad:62:13' LIMIT 1
   (0.3ms)  ROLLBACK

```

Apparently the error occured because the key already exists, so either the gitlab API or the python-gitlab3 are returning an exception that does not correspond to what is really happening.

**Comment by clarete** [comment]
I've got the same error trying to add deploy keys to a project:

```
  File "/Users/lincoln/Work/Personal/dotfiles/.virtualenvs/infra/lib/python2.7/site-packages/gitlab3/__init__.py", line 184, in fn
    data = parent._post(api._uq_url, data=kwargs)
  File "/Users/lincoln/Work/Personal/dotfiles/.virtualenvs/infra/lib/python2.7/site-packages/gitlab3/__init__.py", line 418, in _post
    return self._request(requests.post, api_url, addl_keys, data)
  File "/Users/lincoln/Work/Personal/dotfiles/.virtualenvs/infra/lib/python2.7/site-packages/gitlab3/__init__.py", line 435, in _request
    self._check_status_code(r.status_code, url, data)
  File "/Users/lincoln/Work/Personal/dotfiles/.virtualenvs/infra/lib/python2.7/site-packages/gitlab3/__init__.py", line 411, in _check_status_code
    raise self._code_to_exc[status_code](msg)
gitlab3.exceptions.ResourceNotFound: URL: http://<gitlab>/api/v3/projects/48/keys, Data: {'key': u'ssh-rsa <my-key>', 'title': 'tweety.local'}
```

So I guess it's not caused by an existing key :(

**Comment by clarete** [comment]
My bad, it definitely works. I had the same key in another project (an upload that worked and I didn't see :D)

**Comment by clarete** [comment]
Just wrote a small tool to interact with gitlab deploy keys using gitlab3. I'd definitely be down to open a PR if you guys thing it might be useful: (python-gitlab has one but it doesn't quite work the way I want).

https://gist.github.com/clarete/9421480

**Comment by doctormo** [comment]
More recent testing shows that a key can be added correctly to a user:

```
import gitlab3
gitlab = gitlab3.GitLab('https://gitlab.com', '[REDACTED]')
user = gitlab.get_current_user()
key = user.add_ssh_key(title, key)
key.delete()
```

I've added more listing and deleting options to help the API though.
